GIMNASIO/GIMNASIO/Controllers/CarroController.cs
using GIMNASIO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Controllers
{
    public class CarroController : Controller
    {
        private readonly AppDbContext _context;
        private readonly CarroCompra _carro;

        public CarroController(AppDbContext context, CarroCompra carro)
        {
            _context = context;
            _carro = carro;
        }

        public IActionResult Index()
        {
            ViewData["MetodoPagoId"] = new SelectList(_context.tblMetodoPago.ToList(), "MetodoPagoId", "MetodoNombre");
            ViewData["Id"] = new SelectList(_context.Users.Where(t => t.Tipo == "Cliente").ToList(), "Id", "Rut");
            CarroCompraViewModel carroCompraViewModel = new CarroCompraViewModel()
            {
                carroItems = _carro.GetCarroItems(),
                TotalCarro = _carro.GetTotalCarro()
            };
            return View(carroCompraViewModel);
        }

        public RedirectToActionResult Add(int ProductoId)
        {
            ViewData["MetodoPagoId"] = new SelectList(_context.tblMetodoPago.ToList(), "MetodoPagoId", "MetodoNombre");
            ViewData["id"] = new SelectList(_context.Users.Where(t => t.Tipo.Equals("Cliente")).ToList(), "id", "Rut");
            var P = _context.tblProductos.Where(p => p.ProductoId == ProductoId).FirstOrDefault();
            if (P != null)
            {
                _carro.AddItem(P);
            }
            return RedirectToAction(nameof(Index));
        }

        public RedirectToActionResult Del(int ProductoId)
        {
            var P = _context.tblProductos.Where(p => p.ProductoId == ProductoId).FirstOrDefault();
            if (P != null)
            {
                _carro.delItem(P);
            }
            return RedirectToAction(nameof(Index));
        }


        public RedirectToActionResult AddCart(int ProductoId)
        {
            var P = _context.tblProductos.Where(p => p.ProductoId == ProductoId).FirstOrDefault();
            if (P != null)
            {
                _carro.AddCarro(P);
            }
            return RedirectToAction(nameof(Index));
        }


        public RedirectToActionResult DelCart(int ProductoId)
        {
            var P = _context.tblProductos.Where(p => p.ProductoId == ProductoId).FirstOrDefault();
            if (P != null)
            {
                _carro.delCarro(P);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

GIMNASIO/GIMNASIO/Views/Carro/Index.cshtml
<div class="container">
    @model CarroCompraViewModel

    <div class="container text-center">
        <h2>Carrito de compras</h2>
        <hr>
        <a asp-controller="Home" asp-action="Index" class="btn btn-success pb-2"><i class="fa-solid fa-cart-plus"></i>Agregar</a>

    </div>

    <br>
    <form asp-controller="Pedido" asp-action="Index"  enctype="multipart/form-data">
        <div>

            <table class="table table-striped table-responsive-lg" >
                <thead class="text-center thead-dark">
                    <tr>
                        <td>Imagen</td>
                        <td>Producto</td>
                        <td>Precio Unitario</td>
                        <td>Cantidad</td>
                        <td colspan="2">Añadir/Eliminar</td>
                        <td>Subtotal</td>
                        <td>Eliminar</td>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach (var item in Model.carroItems)
                    {
                    <tr>
                        <td><img src="~/imagen/@item.Producto.imagen" width="50" height="50" /></td>
                        <td>@item.Producto.ProductoNombre</td>
                        <td>@string.Format(new System.Globalization.CultureInfo("es-CL"), "{0:C}", item.Producto.ProductoPrecio)</td>

                        <td>@item.CarroCantidad</td>

                        <!--Cantidad + Sumar y restar cantidad-->
                        <td><a asp-controller="Carro" asp-action="AddCart" asp-route-ProductoId="@item.ProductoId" class="mr-3"><i class="fas fa-plus-circle"></i></a></td>
                        <td><a asp-controller="Carro" asp-action="DelCart" asp-route-ProductoId="@item.ProductoId" class="mr-3"><i class="fas fa-minus-circle"></i></a></td>
                        <td>@string.Format(new System.Globalization.CultureInfo("es-CL"), "{0:C}", item.CarroCantidad * item.Producto.ProductoPrecio)</td>

                        <td><a asp-controller="Carro" asp-action="Del" asp-route-ProductoId="@item.ProductoId" class="mr-3"><i class="fas fa-trash"></i></a></td>
                    </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>   
                        <td class="text-right" colspan="8">
                            Total: @string.Format(new System.Globalization.CultureInfo("es-CL"), "{0:C}", Model.TotalCarro)
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="row justify-content-end">
            <div class="col-md-3 offset-md-1">
                <label asp-for="MetodoPagoId" class="control-label">Método de Pago</label>
                <select asp-for="MetodoPagoId" class="form-control" asp-items="ViewBag.MetodoPagoId"></select>
            </div>

            <div class="col-md-3 offset-md-1">
                <label asp-for="Id" class="control-label">Rut de Cliente</label>
                <select asp-for="Id" class="form-control" asp-items="ViewBag.Id"></select>
            </div>

            <div class="col-md-auto mt-4">
                <input type="submit" value="Finalizar Compra" class="btn btn-primary" />

            </div>
        </div>
    </form>

</div>