GIMNASIO/GIMNASIO/Models/Entrenamiento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Models
{
    public class Entrenamiento
    {
        public int EntrenamientoId { get; set; }

        public int EntrenamientoCupoTotal { get; set; }

        public int EntrenamientoCupoDisponible { get; set; }

        public string EntrenamientoDescripcion { get; set; }

        public int EntrenamientoZonaId { get; set; }
        public EntrenamientoZona entrenamientozona { get; set; }

        public int EntrenamientoEstadoId { get; set; }
        public EntrenamientoEstado entrenamientoestado { get; set; }

        public int EntrenamientoCategoriaId { get; set; }
        public EntrenamientoCategoria entrenamientocategoria { get; set; }

        public Cliente Cliente { get; set; }

    }
}

GIMNASIO/GIMNASIO/Models/EntrenamientoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Models
{
    public class EntrenamientoViewModel
    {
        public List<Entrenamiento> ListarEntrenamiento { get; set; }

        [Display(Name = "Zona de Entrenamiento")]
        public int EntrenamientoZonaId { get; set; }
        public EntrenamientoZona entrenamientozona { get; set; }

        [Display(Name = "Estado de entrenamiento")]
        public int EntrenamientoEstadoId { get; set; }
        public EntrenamientoEstado entrenamientoestado { get; set; }

        [Display(Name = "Categoria")]
        public int EntrenamientoCategoriaId { get; set; }
        public EntrenamientoCategoria entrenamientocategoria { get; set; }

        public Cliente Cliente { get; set; }

    }
}

GIMNASIO/GIMNASIO/Controllers/EntrenamientoController.cs
using GIMNASIO.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Controllers
{
    public class EntrenamientoController : Controller
    {

        private readonly AppDbContext _context;
        private readonly UserManager<Cliente> _userManager;
        private readonly SignInManager<Cliente> _signInManager;

        public EntrenamientoController(UserManager<Cliente> userManager, SignInManager<Cliente> signInManager, AppDbContext context)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult ListarEntrenamiento(EventArgs e)
        {
            EntrenamientoViewModel listaren = new EntrenamientoViewModel();

            listaren.ListarEntrenamiento = _context.tblEntrenamiento
                .Include(e => e.entrenamientocategoria)
               .Include(e => e.entrenamientoestado)
               .Include(e => e.entrenamientozona)
               .ToList();
            return View(listaren);
        }


        public IActionResult CrearEntrenamiento()
        {
            ViewData["EntrenamientoZonaId"] = new SelectList(_context.tblEntrenamientoZona.Where(z => z.EntrenamientoZona_Disponibilidad == true).ToList(), "EntrenamientoZonaId", "EntrenamientoZona_Nombre");
            ViewData["EntrenamientoEstadoId"] = new SelectList(_context.tblEntrenamientoEstado.ToList(), "EntrenamientoEstadoId", "Entrenamiento_NombreEstado");
            ViewData["EntrenamientoCategoriaId"] = new SelectList(_context.tblEntrenamientoCategoria.ToList(), "EntrenamientoCategoriaId", "EntrenamientoCategoria_Nombre");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CrearEntrenamiento(Entrenamiento E)
        {
            var Cliente = await _userManager.GetUserAsync(HttpContext.User);
            if (ModelState.IsValid)
            {
                E.Cliente = Cliente;
                E.EntrenamientoCupoDisponible = E.EntrenamientoCupoTotal;
                _context.Add(E);
                var ZonaEntrenamiento = _context.tblEntrenamientoZona
                    .Where(z => z.EntrenamientoZonaId == E.EntrenamientoZonaId)
                    .FirstOrDefault();
                ZonaEntrenamiento.EntrenamientoZona_Disponibilidad = false;
                await _context.SaveChangesAsync();
                TempData["Mensaje"] = "Maquinaria Agregado Exitosamente!";
                return RedirectToAction(nameof(ListarEntrenamiento));
            }
            return View(E);
        }



        public IActionResult CrearEntrenamientoAdmin()
        {
            ViewData["EntrenadorId"] = new SelectList(_context.Users.Where(t => t.Tipo == "Entrenador").ToList(), "Id", "Rut");
            ViewData["EntrenamientoZonaId"] = new SelectList(_context.tblEntrenamientoZona.Where(z => z.EntrenamientoZona_Disponibilidad == true).ToList(), "EntrenamientoZonaId", "EntrenamientoZona_Nombre");
            ViewData["EntrenamientoEstadoId"] = new SelectList(_context.tblEntrenamientoEstado.ToList(), "EntrenamientoEstadoId", "Entrenamiento_NombreEstado");
            ViewData["EntrenamientoCategoriaId"] = new SelectList(_context.tblEntrenamientoCategoria.ToList(), "EntrenamientoCategoriaId", "EntrenamientoCategoria_Nombre");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CrearEntrenamientoAdmin(EntrenamientoUsuarioViewModel E)
        {
            Entrenamiento en = new Entrenamiento();
            if (ModelState.IsValid)
            {
                var Cliente = _context.Users.Where(e => e.Id == E.EntrenadorID).FirstOrDefault();
                en.EntrenamientoCupoDisponible = E.Entrenamiento.EntrenamientoCupoTotal;
                en.EntrenamientoCupoTotal = E.Entrenamiento.EntrenamientoCupoTotal;
                en.EntrenamientoDescripcion = E.Entrenamiento.EntrenamientoDescripcion;
                en.EntrenamientoEstadoId = E.Entrenamiento.EntrenamientoEstadoId;
                en.EntrenamientoCategoriaId = E.Entrenamiento.EntrenamientoCategoriaId;
                en.EntrenamientoZonaId = E.Entrenamiento.EntrenamientoZonaId;
                en.Cliente = Cliente;
                _context.Add(en);
                var ZonaEntrenamiento = _context.tblEntrenamientoZona
                    .Where(z => z.EntrenamientoZonaId == E.Entrenamiento.EntrenamientoZonaId)
                    .FirstOrDefault();
                ZonaEntrenamiento.EntrenamientoZona_Disponibilidad = false;
                await _context.SaveChangesAsync();
                TempData["Mensaje"] = "Entrenamiento Agregado Exitosamente!";
                return RedirectToAction(nameof(ListarEntrenamiento));
            }
            return View(E);
        }

        //Eliminar
        [HttpGet]
        public IActionResult EliminarEntrenamiento(int EntrenamientoId)
        {
            ViewData["EntrenamientoZonaId"] = new SelectList(_context.tblEntrenamientoZona.ToList(), "EntrenamientoZonaId", "EntrenamientoZona_Nombre");
            ViewData["EntrenamientoEstadoId"] = new SelectList(_context.tblEntrenamientoEstado.ToList(), "EntrenamientoEstadoId", "Entrenamiento_NombreEstado");
            ViewData["EntrenamientoCategoriaId"] = new SelectList(_context.tblEntrenamientoCategoria.ToList(), "EntrenamientoCategoriaId", "EntrenamientoCategoria_Nombre");
            var E = _context.tblEntrenamiento.Where(e => e.EntrenamientoId.Equals(EntrenamientoId))
               .Include(e => e.entrenamientocategoria)
               .Include(e => e.entrenamientoestado)
               .Include(e => e.entrenamientozona).FirstOrDefault();
            return View(E);
        }

        [HttpPost]
        public async Task<IActionResult> EliminarEntrenamiento(Entrenamiento E)
        {
            var EntrenamientoEliminado = _context.tblEntrenamiento.Where(e => e.EntrenamientoId == E.EntrenamientoId).FirstOrDefault();
            var ZonaActual = _context.tblEntrenamientoZona
                    .Where(za => za.EntrenamientoZonaId == E.EntrenamientoZonaId)
                    .FirstOrDefault();
            ZonaActual.EntrenamientoZona_Disponibilidad = true;
            _context.Entry(EntrenamientoEliminado).State = EntityState.Deleted;
            await _context.SaveChangesAsync();
            TempData["Mensaje"] = "Entrenamiento Eliminado Exitosamente!";
            return RedirectToAction(nameof(ListarEntrenamiento));
        }

        //Editar Entrenamiento  
        public IActionResult ModificarEntrenamiento(int EntrenamientoId)
        {
            ViewData["EntrenamientoZonaId"] = new SelectList(_context.tblEntrenamientoZona.ToList(), "EntrenamientoZonaId", "EntrenamientoZona_Nombre");
            ViewData["EntrenamientoEstadoId"] = new SelectList(_context.tblEntrenamientoEstado.ToList(), "EntrenamientoEstadoId", "Entrenamiento_NombreEstado");
            ViewData["EntrenamientoCategoriaId"] = new SelectList(_context.tblEntrenamientoCategoria.ToList(), "EntrenamientoCategoriaId", "EntrenamientoCategoria_Nombre");
            var E = _context.tblEntrenamiento.Where(e => e.EntrenamientoId.Equals(EntrenamientoId)).FirstOrDefault();
            return View(E);
        }

        [HttpPost]
        public async Task<IActionResult> ModificarEntrenamiento(Entrenamiento E)
        {
            if (ModelState.IsValid)
            {
                var EntrenamientoModificada = _context.tblEntrenamiento.Where(e => e.EntrenamientoId.Equals(e.EntrenamientoId)).FirstOrDefault();

                var ZonaActual = _context.tblEntrenamientoZona
                    .Where(za => za.EntrenamientoZonaId == EntrenamientoModificada.EntrenamientoZonaId)
                    .FirstOrDefault();
                var ZonaNueva = _context.tblEntrenamientoZona
                    .Where(zn => zn.EntrenamientoZonaId == E.EntrenamientoZonaId)
                    .FirstOrDefault();

                EntrenamientoModificada.EntrenamientoCupoTotal = E.EntrenamientoCupoTotal;
                EntrenamientoModificada.EntrenamientoCupoDisponible = E.EntrenamientoCupoDisponible;
                EntrenamientoModificada.EntrenamientoDescripcion = E.EntrenamientoDescripcion;
                EntrenamientoModificada.EntrenamientoEstadoId = E.EntrenamientoEstadoId;
                EntrenamientoModificada.EntrenamientoZonaId = E.EntrenamientoZonaId;
                EntrenamientoModificada.EntrenamientoCategoriaId = E.EntrenamientoCategoriaId;

                ZonaActual.EntrenamientoZona_Disponibilidad = true;
                ZonaNueva.EntrenamientoZona_Disponibilidad = false;

                await _context.SaveChangesAsync();
                TempData["Mensaje"] = "Entrenamiento Modificado Exitosamente!";
                return RedirectToAction(nameof(ListarEntrenamiento));
            }
            else
            {
                return View(E);
            }
        }

        public IActionResult DetalleEntrenamiento(int EntrenamientoId)
        {
            EntrenamientoUsuarioViewModel euvm = new EntrenamientoUsuarioViewModel();

            euvm.Entrenamiento = _context.tblEntrenamiento
               .Include(e => e.entrenamientocategoria)
               .Include(e => e.entrenamientoestado)
               .Include(e => e.entrenamientozona)
               .Include(e=> e.Cliente)
               .Where(e => e.EntrenamientoId == EntrenamientoId)
               .FirstOrDefault();

            euvm.ListaEntrenamiento = _context.tblEntrenamientoUsuario
                .Include(eu => eu.Cliente)
                .Where(eu => eu.EntrenamientoId == EntrenamientoId && eu.Cliente.Tipo == "Cliente")
                .ToList();
            return View(euvm);
        }

GIMNASIO/GIMNASIO/Views/Entrenamiento/CrearEntrenamiento.cshtml
@model GIMNASIO.Models.Entrenamiento

@{
    ViewData["Title"] = "Crear Entrenamiento";
}

<div class="container text-center">
    <h2>Registro de Entrenamiento</h2>
    <hr>
</div>
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="CrearEntrenamiento">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EntrenamientoCupoTotal" class="control-label">Cupo Total</label>
                <input asp-for="EntrenamientoCupoTotal" class="form-control" />
                <span asp-validation-for="EntrenamientoCupoTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntrenamientoDescripcion" class="control-label">Descripción</label>
                <input asp-for="EntrenamientoDescripcion" class="form-control" />
                <span asp-validation-for="EntrenamientoDescripcion" class="text-danger"></span>
            </div>

            <!--Seleccionar estado-->
            <div class="form-group">
                <label asp-for="EntrenamientoZonaId" class="control-label">Zona disponible</label>
                <select asp-for="EntrenamientoZonaId" class="form-control" asp-items="ViewBag.EntrenamientoZonaId"></select>
            </div>

            <!--Seleccionar estado-->
            <div class="form-group">
                <label asp-for="EntrenamientoEstadoId" class="control-label">Estado</label>
                <select asp-for="EntrenamientoEstadoId" class="form-control" asp-items="ViewBag.EntrenamientoEstadoId"></select>
            </div>
            <!--Seleccionar estado-->
            <div class="form-group">
                <label asp-for="EntrenamientoCategoriaId" class="control-label">Categoría</label>
                <select asp-for="EntrenamientoCategoriaId" class="form-control" asp-items="ViewBag.EntrenamientoCategoriaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear Entrenamiento" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GIMNASIO/GIMNASIO/Views/Entrenamiento/CrearEntrenamientoAdmin.cshtml
@model GIMNASIO.Models.EntrenamientoUsuarioViewModel

@{
    ViewData["Title"] = "Crear Entrenamiento";
}

<div class="container text-center">
    <h2>Registro de Entrenamiento</h2>
    <hr>
</div>
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="CrearEntrenamientoAdmin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Entrenamiento.EntrenamientoCupoTotal" class="control-label">Cupo Total</label>
                <input asp-for="Entrenamiento.EntrenamientoCupoTotal" class="form-control" />
                <span asp-validation-for="Entrenamiento.EntrenamientoCupoTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Entrenamiento.EntrenamientoDescripcion" class="control-label">Descripción</label>
                <input asp-for="Entrenamiento.EntrenamientoDescripcion" class="form-control" />
                <span asp-validation-for="Entrenamiento.EntrenamientoDescripcion" class="text-danger"></span>
            </div>

            <!--Seleccionar estado-->
            <div class="form-group">
                <label asp-for="Entrenamiento.EntrenamientoZonaId" class="control-label">Zona disponible</label>
                <select asp-for="Entrenamiento.EntrenamientoZonaId" class="form-control" asp-items="ViewBag.EntrenamientoZonaId"></select>
            </div>

            <!--Seleccionar estado-->
            <div class="form-group">
                <label asp-for="Entrenamiento.EntrenamientoEstadoId" class="control-label">Estado</label>
                <select asp-for="Entrenamiento.EntrenamientoEstadoId" class="form-control" asp-items="ViewBag.EntrenamientoEstadoId"></select>
            </div>
            <!--Seleccionar estado-->
            <div class="form-group">
                <label asp-for="Entrenamiento.EntrenamientoCategoriaId" class="control-label">Categoría</label>
                <select asp-for="Entrenamiento.EntrenamientoCategoriaId" class="form-control" asp-items="ViewBag.EntrenamientoCategoriaId"></select>
            </div>

            <div class="form-group">
                <label asp-for="EntrenadorID" class="control-label">Entrenador</label>
                <select asp-for="EntrenadorID" class="form-control" asp-items="ViewBag.EntrenadorId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear Entrenamiento" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GIMNASIO/GIMNASIO/Views/Entrenamiento/DetalleEntrenamiento.cshtml
@model GIMNASIO.Models.EntrenamientoUsuarioViewModel

@{
    ViewData["Title"] = "DetalleEntrenamiento";
}

<div class="container text-center">
    <h2>Detalle del Entrenamiento</h2>
    <hr>
</div>
<br />

@if (TempData["Mensaje"] != null)
{
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        @TempData["Mensaje"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <br />
}

<div class="card mb-3">
    <div class="card-body justify-content-center text-center">
        <div class="row mt-2 mb-3">
            <div class="col-xl-6 col-md-12 col-sm-12">
                <div class="col"><h5><b>Cupo Total: </b>@Model.Entrenamiento.EntrenamientoCupoTotal</h5></div>
            </div>
            <div class="col-xl-6 col-md-12 col-sm-12">
                <div class="col"><h5><b>Cupo Disponible: </b>@Model.Entrenamiento.EntrenamientoCupoDisponible</h5></div>
            </div>
            <div class="col-xl-4 col-md-12 col-sm-12">
                <div class="col"><h5><b>Zona: </b>@Model.Entrenamiento.entrenamientozona.EntrenamientoZona_Nombre</h5></div>
            </div>
            <div class="col-xl-4 col-md-12 col-sm-12">
                <div class="col"><h5><b>Estado: </b>@Model.Entrenamiento.entrenamientoestado.Entrenamiento_NombreEstado</h5></div>
            </div>
            <div class="col-xl-4 col-md-12 col-sm-12">
                <div class="col"><h5><b>Categoría: </b>@Model.Entrenamiento.entrenamientocategoria.EntrenamientoCategoria_Nombre</h5></div>
            </div>
            <div class="col-12">
                <div class="col"><h5><b>Entrenador: </b>@Model.Entrenamiento.Cliente.Nombres @Model.Entrenamiento.Cliente.ApellidoP  @Model.Entrenamiento.Cliente.ApellidoM</h5></div>
            </div>
            <div class="col-12">
                <div class="col"><h5><b>Descripción: </b>@Model.Entrenamiento.EntrenamientoDescripcion</h5></div>
            </div>
        </div>
    </div>
</div>

<div class="container text-center">
    <h3>Lista de Asistentes</h3>
</div>

<br />
<table class="table table-striped table-responsive-lg">
    <thead>
        <tr>
            <th>
                Rut
            </th>
            <th>
                Nombre
            </th>
            <th>
                Correo
            </th>
            <th>
                Teléfono
            </th>
            <th>
                Eliminar
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var E in Model.ListaEntrenamiento)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => E.Cliente.Rut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => E.Cliente.Nombres) @Html.DisplayFor(modelItem => E.Cliente.ApellidoP) @Html.DisplayFor(modelItem => E.Cliente.ApellidoM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => E.Cliente.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => E.Cliente.Telefono)
            </td>
            <td>
                <a asp-action="EliminarClienteDeEntrenamiento"
                   asp-controller="Entrenamiento" 
                    class="btn btn-primary" 
                    asp-route-EntrenamientoId="@E.entrenamiento.EntrenamientoId"
                    asp-route-ClienteId="@E.Cliente.Id">
                    Dar de baja
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>

GIMNASIO/GIMNASIO/Views/Entrenamiento/EliminarEntrenamiento.cshtml
@model GIMNASIO.Models.Entrenamiento

@{
    ViewData["Title"] = "Eliminar Entrenamiento";
}


<div class="container text-center">
    <h2>Eliminar Entrenamiento</h2>
    <h3>¿Está seguro de eliminar este entrenamiento? Si lo elimina no podrá recuperarlo.</h3>
    <hr>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Cupo Total:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EntrenamientoCupoTotal)
        </dd>
        <dt class="col-sm-2">
            Cupo disponible
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EntrenamientoCupoDisponible)
        </dd>
        <dt class="col-sm-2">
            Descripcion:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EntrenamientoDescripcion)
        </dd>
        <dt class="col-sm-2">
            Zona de entrenamiento:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.entrenamientozona.EntrenamientoZona_Nombre)
        </dd>
        <dt class="col-sm-2">
            Estado:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.entrenamientoestado.Entrenamiento_NombreEstado)
        </dd>
        <dt class="col-sm-2">
            Categoria:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.entrenamientocategoria.EntrenamientoCategoria_Nombre)
        </dd>
    </dl>

    <form asp-action="EliminarEntrenamiento">
        <input type="hidden" asp-for="EntrenamientoId" />
        <input type="hidden" asp-for="EntrenamientoZonaId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
    </form>
</div>

GIMNASIO/GIMNASIO/Views/Entrenamiento/ListarEntrenamiento.cshtml
@model EntrenamientoViewModel

<div class="container text-center">
    <h2>Entrenamientos</h2>
    <hr>
    @{var Acceso = User.Claims.Where(x => x.Type == "Admin").FirstOrDefault();}
    @if (Acceso != null)
    {
        <a asp-controller="Entrenamiento" asp-action="CrearEntrenamientoAdmin" class="btn btn-success pb-2"><i class="fa-solid fa-plus"></i> Agregar</a>

    }
    else
    {
        <a asp-controller="Entrenamiento" asp-action="CrearEntrenamiento" class="btn btn-success pb-2"><i class="fa-solid fa-plus"></i> Agregar</a>

    }
</div>
<br />

@if (TempData["Mensaje"] != null)
{
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        @TempData["Mensaje"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<br />
<table class="table table-striped table-responsive-lg ">
    <thead>
        <tr>
            <th>
                Cupo total
            </th>
            <th>
                Cupo disponible
            </th>
            <th>
                Zona de Entrenamiento
            </th>
            <th>
                Estado del Entrenamiento
            </th>
            <th>
                Categoria
            </th>
            <th>
                Eliminar
            </th>
            <th>
                Detalles
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var E in Model.ListarEntrenamiento)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => E.EntrenamientoCupoTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => E.EntrenamientoCupoDisponible)
            </td>
            <td>
                @Html.DisplayFor(modelItem => E.entrenamientozona.EntrenamientoZona_Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => E.entrenamientoestado.Entrenamiento_NombreEstado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => E.entrenamientocategoria.EntrenamientoCategoria_Nombre)
            </td>
            <td>
                <a asp-action="EliminarEntrenamiento" class="btn btn-danger" asp-route-EntrenamientoId="@E.EntrenamientoId">Eliminar</a>
            </td>
            <td>
                <a asp-action="DetalleEntrenamiento" class="btn btn-primary" asp-route-EntrenamientoId="@E.EntrenamientoId">Detalles</a>
            </td>
        </tr>
        }
    </tbody>
</table>

GIMNASIO/GIMNASIO/Views/Entrenamiento/ModificarEntrenamiento.cshtml
@model GIMNASIO.Models.Entrenamiento

@{
    ViewData["Title"] = "ModificarEntrenamiento";
}

<div class="container text-center">
    <h2>Edición de Entrenamiento</h2>
    <hr>
</div>
<br>

<div class="row">
    <div class="col-md-4">
        <form asp-action="ModificarEntrenamiento">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EntrenamientoId" />
            <div class="form-group">
                <label asp-for="EntrenamientoCupoTotal" class="control-label">Cupo Total</label>
                <input asp-for="EntrenamientoCupoTotal" class="form-control" />
                <span asp-validation-for="EntrenamientoCupoTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntrenamientoCupoDisponible" class="control-label">Cupo Disponible</label>
                <input asp-for="EntrenamientoCupoDisponible" class="form-control" />
                <span asp-validation-for="EntrenamientoCupoDisponible" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntrenamientoDescripcion" class="control-label">Descripción</label>
                <input asp-for="EntrenamientoDescripcion" class="form-control" />
                <span asp-validation-for="EntrenamientoDescripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntrenamientoZonaId" class="control-label">Zona de Entrenamiento</label>
                <select asp-for="EntrenamientoZonaId" class="form-control" asp-items="ViewBag.EntrenamientoZonaId"></select>
                <span asp-validation-for="EntrenamientoZonaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntrenamientoEstadoId" class="control-label">Estado</label>
                <select asp-for="EntrenamientoEstadoId" class="form-control" asp-items="ViewBag.EntrenamientoEstadoId"></select>
                <span asp-validation-for="EntrenamientoEstadoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntrenamientoCategoriaId" class="control-label">Categoría</label>
                <select asp-for="EntrenamientoCategoriaId" class="form-control" asp-items="ViewBag.EntrenamientoCategoriaId"></select>
                <span asp-validation-for="EntrenamientoCategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Modificar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}