GIMNASIO/GIMNASIO/Models/AvanceViewModel.cs
using System;
using System.Collections.Generic;

namespace GIMNASIO.Models
{
    public class AvanceViewModel
    {
        public List<AvanceCliente> ListaAvance { get; set; }
        public Double AvanceCliente_Peso { get; set; }

        public Double AvanceCliente_Altura { get; set; }

        public float AvanceCliente_IMC { get; set; }
        
        public DateTime AvanceCliente_Fecha { get; set; }
        public string AvanceCliente_Situacion { get; set; }
        public string Id { get; set; }

    }
}

GIMNASIO/GIMNASIO/Controllers/AvanceController.cs
using GIMNASIO.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Controllers
{
    [Authorize(Policy = "PolicyAdmin")]
    public class AvanceController : Controller
    {
        private readonly AppDbContext _context;

        public AvanceController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult ListaAvancePorCliente(Cliente C)
        {
            AvanceViewModel avm = new AvanceViewModel();
            var Cliente = _context.Users
                   .Where(c => c.Id == C.Id).FirstOrDefault();
            avm.ListaAvance = _context.tblAvanceCliente
                    .Where(a => a.Cliente == C).ToList();
            avm.Id = Cliente.Id;
            return View(avm);
        }

        public IActionResult AgregarAvance(string ClienteId)
        {
            var cliente = _context.Users.Where(c => c.Id == ClienteId).FirstOrDefault();

            AvanceViewModel avm = new AvanceViewModel
            {
                Id = cliente.Id
            };

            return View(avm);
        }

        [HttpPost]
        public IActionResult AgregarAvance(AvanceViewModel avm)
        {
            if (ModelState.IsValid)
            {
                var Cliente = _context.Users.Where(u => u.Id == avm.Id).FirstOrDefault();

                var Imc = avm.AvanceCliente_Peso / (avm.AvanceCliente_Altura * avm.AvanceCliente_Altura);

                
                switch (Imc)
                {
                    case var n when n < 18.5:
                        avm.AvanceCliente_Situacion = "Insuficiencia Ponderada";
                        break;
                    case var n when n >= 18.5 && n < 25:
                        avm.AvanceCliente_Situacion = "Intervalo normal";
                        break;
                    case var n when n >= 25 && n < 30:
                        avm.AvanceCliente_Situacion = "Sobrepeso";
                        break;
                    case var n when n >= 30 && n < 35:
                        avm.AvanceCliente_Situacion = "Obesidad 1";
                        break;
                    case var n when n >= 35 && n < 40:
                        avm.AvanceCliente_Situacion = "Obesidad 2";
                        break;
                    case var n when n >= 40:
                        avm.AvanceCliente_Situacion = "Obesidad 3";
                        break;
                }

                AvanceCliente avance = new AvanceCliente();
                avance.AvanceCliente_Altura = avm.AvanceCliente_Altura;
                avance.AvanceCliente_Peso = avm.AvanceCliente_Peso;
                avance.AvanceCliente_Fecha = avm.AvanceCliente_Fecha;
                avance.AvanceCliente_Situacion = avm.AvanceCliente_Situacion;
                avance.AvanceCliente_IMC = ((float)Imc);
                avance.Cliente = Cliente;
                _context.Add(avance);
                _context.SaveChanges();

                return RedirectToAction("ListaAvancePorCliente", Cliente);
            }

            return View(avm.Id);
            
        }
    }
}

GIMNASIO/GIMNASIO/Views/Avance/AgregarAvance.cshtml
<div class="container">
    @model AvanceViewModel


    <div class="text-center">
        <h2>Nuevo Avance de Cliente</h2>
        <hr>
    </div>
    <br>

    <div class="row">
        <form class="col-md-12" asp-action="AgregarAvance">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="AvanceCliente_Peso" class="control-label">Peso</label>
                        <input asp-for="AvanceCliente_Peso" step=".1" type="number" class="form-control" />
                        <span asp-validation-for="AvanceCliente_Peso" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AvanceCliente_Altura" class="control-label">Altura</label>
                        <input asp-for="AvanceCliente_Altura" step=".01" type="number" class="form-control" />
                        <span asp-validation-for="AvanceCliente_Altura" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AvanceCliente_Fecha" class="control-label">Fecha de Avance</label>
                        <input asp-for="AvanceCliente_Fecha" type="date" class="form-control" />
                        <span asp-validation-for="AvanceCliente_Fecha" class="text-danger"></span>
                    </div>
                </div>

                <input asp-for="Id" type="hidden"/>

                <input type="submit" value="Guardar" class="btn btn-outline-info btn-block" />

            </div>
        </form>
    </div>
</div>

GIMNASIO/GIMNASIO/Views/Avance/ListaAvancePorCliente.cshtml
@model AvanceViewModel

<div class="container text-center">
    <h2>Avance de Cliente</h2>
    <hr>
    <a asp-controller="Avance" asp-action="AgregarAvance" asp-route-ClienteId="@Model.Id" class="btn btn-success pb-2"><i class="fa-solid fa-plus"></i> Agregar</a>
</div>
<br>

<table class="table table-striped">
    <thead class="text-center thead-dark">
        <tr>
            <td>Fecha</td>
            <td>Peso</td>
            <td>Altura</td>
            <td>IMC</td>
            <td>Avance</td>
            <td>Editar</td>
            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody class="text-center">
        @foreach (var A in Model.ListaAvance)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => A.AvanceCliente_Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => A.AvanceCliente_Peso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => A.AvanceCliente_Altura)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => A.AvanceCliente_IMC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => A.AvanceCliente_Situacion)
                </td>
                <td><a asp-action="ModificarAvance" asp-route-Id="@A.AvanceClienteId" asp-route-ClienteId="@A.AvanceClienteId" class="ml-4 btn btn-warning text-white"><i class="fa-solid fa-file-pen"></i></a></td>
                <td><a asp-action="EliminarAvance" asp-route-Id="@A.AvanceClienteId" class="mr-4 btn btn-danger"><i class="fa-solid fa-trash-can"></i></a></td>
            </tr>
        }
    </tbody>
</table>