GIMNASIO/GIMNASIO/Models/EntrenamientoUsuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Models
{
    public class EntrenamientoUsuario
    {
        public int EntrenamientoUsuarioId { get; set; }

        public Cliente Cliente { get; set; }

        public int EntrenamientoId { get; set; }
        public Entrenamiento entrenamiento { get; set; }

    }
}

GIMNASIO/GIMNASIO/Models/EntrenamientoUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Models
{
    public class EntrenamientoUsuarioViewModel
    {
        public Cliente cliente { get; set; }

        public List<EntrenamientoUsuario> ListaEntrenamiento { get; set; }

        public Entrenamiento Entrenamiento { get; set; }
        public string EntrenadorID { get; set; }
    }
}

GIMNASIO/GIMNASIO/Controllers/EntrenamientoUsuarioController.cs
using GIMNASIO.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GIMNASIO.Controllers
{
    public class EntrenamientoUsuarioController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<Cliente> _userManager;
        private readonly SignInManager<Cliente> _signInManager;
        public EntrenamientoUsuarioController(UserManager<Cliente> userManager, SignInManager<Cliente> signInManager,
            AppDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        public IActionResult ListarEntrenamiento(EventArgs e)
        {
            EntrenamientoViewModel listaren = new EntrenamientoViewModel();

            listaren.ListarEntrenamiento = _context.tblEntrenamiento
                .Include(e => e.entrenamientocategoria).Include(e => e.Cliente)
               .Include(e => e.entrenamientoestado)
               .Include(e => e.entrenamientozona).Where(e => (e.EntrenamientoEstadoId == 1 || e.EntrenamientoEstadoId == 2) && e.EntrenamientoCupoDisponible > 0).ToList();
            return View(listaren);
        }

        public async Task<IActionResult> EntrenamiendoAnadir(EntrenamientoUsuario EN, int EntrenamientoId)
        {
            var Cliente = await _userManager.GetUserAsync(HttpContext.User);
            var Entrenamiento = _context.tblEntrenamiento.Where(e => e.EntrenamientoId.Equals(EntrenamientoId)).FirstOrDefault();
            if (ModelState.IsValid)
            {

                EN.Cliente = Cliente;
                EN.entrenamiento = Entrenamiento;
                _context.Add(EN);
                Entrenamiento.EntrenamientoCupoDisponible--;
                if (Entrenamiento.EntrenamientoCupoDisponible <= 10)
                {
                    Entrenamiento.EntrenamientoEstadoId = 2;
                }
                if (Entrenamiento.EntrenamientoCupoDisponible == 0)
                {
                    Entrenamiento.EntrenamientoEstadoId = 4;
                }

                await _context.SaveChangesAsync();
                TempData["Mensaje"] = "Inscripción Exitosa!";
                return RedirectToAction(nameof(ListarEntrenamiento));
            }
            return View(EN);
        }

  

        public async Task<IActionResult> MisEntrenamientos()
        {
            var Cliente = await _userManager.GetUserAsync(HttpContext.User);
            EntrenamientoUsuarioViewModel EU = new EntrenamientoUsuarioViewModel
            {
                cliente = Cliente,
                ListaEntrenamiento = _context.tblEntrenamientoUsuario
                .Include(c => c.entrenamiento.entrenamientocategoria)
               .Include(e => e.entrenamiento.entrenamientoestado)
               .Include(e => e.entrenamiento.Cliente)
               .Include(e => e.entrenamiento.entrenamientozona)
               .Where(e => e.Cliente.Id == Cliente.Id)
               .ToList()
            };
            return View(EU);
        }

        




    }
}

GIMNASIO/GIMNASIO/Views/EntrenamientoUsuario/ListarEntrenamiento.cshtml
@model EntrenamientoViewModel



<div class="container">



    @if (TempData["Mensaje"] != null)
    {
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            @TempData["Mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }



    <div class="container text-center">
        <h2>Entrenamientos</h2>
        <hr>
    </div>



    <div class="row justify-content-between">






        @foreach (var E in Model.ListarEntrenamiento)
        {
            <div class="col-md-12 col-lg-3 mr-3 ml-3 mb-3">
                <div class="card card-producto" style="width: 18rem;">
                    <div class="card-body">
                        <P class="card-text detalles-card-producto">Cupo Total: @E.EntrenamientoCupoTotal</P>
                        <P class="card-text detalles-card-producto">Cupo Disponible: @E.EntrenamientoCupoDisponible</P>
                        <P class="card-text detalles-card-producto">Descripción: @E.EntrenamientoDescripcion</P>
                        <P class="card-text detalles-card-producto">Estado: @E.entrenamientoestado.Entrenamiento_NombreEstado</P>
                        <P class="card-text detalles-card-producto">Categoría: @E.entrenamientocategoria.EntrenamientoCategoria_Nombre</P>
                        <P class="card-text detalles-card-producto">Zona de entrenamiento: @E.entrenamientozona.EntrenamientoZona_Nombre</P>
                        <P class="card-text detalles-card-producto">Entrenador: @E.Cliente.Nombres</P>
                    </div>



                    <div class="row justify-content-around botones-productos">
                        <div class="col-4">
                            <a class="btn btn-success" asp-action="EntrenamiendoAnadir" asp-controller="EntrenamientoUsuario" asp-route-EntrenamientoId="@E.EntrenamientoId">
                                <i class="fa-solid fa-cart-arrow-down"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

GIMNASIO/GIMNASIO/Views/EntrenamientoUsuario/MisEntrenamientos.cshtml
<div>
    <div class="container">
        @model EntrenamientoUsuarioViewModel

        @{
            ViewData["Title"] = "Mis Entrenamientos";
            Layout = "~/Views/Shared/_Layout.cshtml";
        }

        <div style="background-color: #00ffff" class="card card-cascade narrower view view-cascade gradient-card-header blue-gradient narrower py-2 mb-3 d-flex justify-content-between align-items-center">
            <h2 href="" class="white-text mx-3">Historial de Entrenamientos</h2>
        </div>

        <hr />

        <table class="table table-striped">
            <thead style="background-color:#00ffff">
                <tr>
                    <td>Rut</td>
                    <td>Nombre</td>
                    <td>Apellido</td>
                    <td>Dirección</td>
                    <td>Correo</td>
                    <td>Ciudad</td>
                    <td><strong>Teléfono: </strong></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.cliente.Rut</td>
                    <td>@Model.cliente.Nombres</td>
                    <td>@Model.cliente.ApellidoP</td>
                    <td>@Model.cliente.Direccion</td>
                    <td>@Model.cliente.Email</td>
                    <td>@Model.cliente.Ciudad</td>
                    <td>@Model.cliente.Telefono</td>
                </tr>

            </tbody>
        </table>

        <br />

        <div class="row justify-content-between">
            @foreach (var P in Model.ListaEntrenamiento)
            {
                <div class="card mr-3 ml-3 mb-3" style="width: 18rem;">
                    <div class="card" style="width: 18rem;">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><strong>Descripción: </strong>@P.entrenamiento.EntrenamientoDescripcion</li>
                            <li class="list-group-item"><strong>Estado: </strong>@P.entrenamiento.entrenamientoestado.Entrenamiento_NombreEstado</li>
                            <li class="list-group-item"><strong>Zona: </strong>@P.entrenamiento.entrenamientozona.EntrenamientoZona_Nombre</li>
                            <li class="list-group-item"><strong>Categoría: </strong>@P.entrenamiento.entrenamientocategoria.EntrenamientoCategoria_Nombre</li>
                            <li class="list-group-item"><strong>Entrenador: </strong>@P.entrenamiento.Cliente.Nombres @P.entrenamiento.Cliente.ApellidoP @P.entrenamiento.Cliente.ApellidoM </li>
                        </ul>
                    </div>
                </div>
            }
        </div>

        <br />
        <div>
            <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index" style="margin-left: 500px">
                Volver Home
            </a>
        </div>
    </div>
</div>